### ISSUE TITLE
4.39.0 breaks beaker-puppet tests

### ISSUE THREAD

**Issue by evgeni** [voxpupuli/beaker#1772]
`beaker-puppet` tests are broken with beaker 4.39.0 (but work fine with 4.38.1):

```
Failures:

  1) ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on raises an exception when host platform is unsupported
     Failure/Error:
       expect{
         subject.install_puppet_agent_dev_repo_on( host, opts )
       }.to raise_error(RuntimeError, /No repository installation step for/)
     
       expected RuntimeError with message matching /No repository installation step for/, got #<NoMethodError: undefined method `variant' for #<Object:0x00007fd43ad48ee0>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^> with backtrace:
         # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
         # ./lib/beaker-puppet/install_utils/foss_utils.rb:1281:in `block in install_puppet_agent_dev_repo_on'
         # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
         # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
         # ./lib/beaker-puppet/install_utils/foss_utils.rb:1264:in `install_puppet_agent_dev_repo_on'
         # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1071:in `block (4 levels) in <top (required)>'
         # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1070:in `block (3 levels) in <top (required)>'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1070:in `block (3 levels) in <top (required)>'

  2) ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct install for el-based platforms
     Failure/Error: onhost_copy_base = opts[:copy_dir_external] || host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43a616910>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1281:in `block in install_puppet_agent_dev_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1264:in `install_puppet_agent_dev_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1088:in `block (3 levels) in <top (required)>'

  3) ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct install for el-based platforms on s390x architectures
     Failure/Error: onhost_copy_base = opts[:copy_dir_external] || host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43a5972f0>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1281:in `block in install_puppet_agent_dev_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1264:in `install_puppet_agent_dev_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1112:in `block (3 levels) in <top (required)>'

  4) ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct agent install for el-based platforms on ec2 hypervisor
     Failure/Error: onhost_copy_base = opts[:copy_dir_external] || host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43a514a80>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1281:in `block in install_puppet_agent_dev_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1264:in `install_puppet_agent_dev_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1137:in `block (3 levels) in <top (required)>'

  5) ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct install for debian-based platforms
     Failure/Error: onhost_copy_base = opts[:copy_dir_external] || host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43a4a3ec0>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1281:in `block in install_puppet_agent_dev_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1264:in `install_puppet_agent_dev_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1153:in `block (3 levels) in <top (required)>'

  6) ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on allows you to override the local copy directory
     Failure/Error: onhost_copy_base = opts[:copy_dir_external] || host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43b9b9da0>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1281:in `block in install_puppet_agent_dev_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1264:in `install_puppet_agent_dev_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1243:in `block (3 levels) in <top (required)>'

  7) ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths when agent version is set to latest
     Failure/Error: opts[:copy_dir_external]  ||= host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43a46f260>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1373:in `block in install_puppet_agent_pe_promoted_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1368:in `install_puppet_agent_pe_promoted_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1424:in `block (4 levels) in <top (required)>'

  8) ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths for agent version 1.x.x
     Failure/Error: opts[:copy_dir_external]  ||= host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43b1745c8>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1373:in `block in install_puppet_agent_pe_promoted_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1368:in `install_puppet_agent_pe_promoted_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1444:in `block (4 levels) in <top (required)>'

  9) ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths for agent version >= 5.5.4
     Failure/Error: opts[:copy_dir_external]  ||= host.external_copy_base
     
     NoMethodError:
       undefined method `variant' for #<Object:0x00007fd43ad37848>
     
               if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                  ^^^^^^^^
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1373:in `block in install_puppet_agent_pe_promoted_repo_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
     # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
     # ./lib/beaker-puppet/install_utils/foss_utils.rb:1368:in `install_puppet_agent_pe_promoted_repo_on'
     # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1465:in `block (4 levels) in <top (required)>'

  10) ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths for agent version > 5.99
      Failure/Error: opts[:copy_dir_external]  ||= host.external_copy_base
      
      NoMethodError:
        undefined method `variant' for #<Object:0x00007fd43a633ba0>
      
                if self['platform'].variant == 'solaris' && self['platform'].version == '10'
                                   ^^^^^^^^
      # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/host/unix.rb:39:in `external_copy_base'
      # ./lib/beaker-puppet/install_utils/foss_utils.rb:1373:in `block in install_puppet_agent_pe_promoted_repo_on'
      # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/shared/host_manager.rb:129:in `run_block_on'
      # ./vendor/bundle/ruby/3.1.0/gems/beaker-4.39.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
      # ./lib/beaker-puppet/install_utils/foss_utils.rb:1368:in `install_puppet_agent_pe_promoted_repo_on'
      # ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1486:in `block (4 levels) in <top (required)>'

Finished in 0.90172 seconds (files took 0.33753 seconds to load)
405 examples, 10 failures

Failed examples:

rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1062 # ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on raises an exception when host platform is unsupported
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1075 # ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct install for el-based platforms
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1091 # ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct install for el-based platforms on s390x architectures
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1115 # ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct agent install for el-based platforms on ec2 hypervisor
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1140 # ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on runs the correct install for debian-based platforms
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1222 # ClassMixedWithDSLInstallUtils#install_puppet_agent_dev_repo_on allows you to override the local copy directory
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1406 # ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths when agent version is set to latest
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1427 # ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths for agent version 1.x.x
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1447 # ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths for agent version >= 5.5.4
rspec ./spec/beaker-puppet/install_utils/foss_utils_spec.rb:1468 # ClassMixedWithDSLInstallUtils#install_puppet_agent_pe_promoted_repo_on when setting different agent versions sets correct file paths for agent version > 5.99
```

My suspicion is this commit: https://github.com/voxpupuli/beaker/commit/3f000d3c22ac9e2bbdba4eb6f73f6d1b238f156b

**Comment by ekohl** [comment]
So I assumed `self['platform']` was always an instance of `Beaker::Platform` but in `beaker-puppet` it's mocked as an object that "implements `to_array`:
https://github.com/voxpupuli/beaker-puppet/blob/9b94c4c5d49ae0be1b8a20542fde26319af244d0/spec/beaker-puppet/install_utils/foss_utils_spec.rb#L1397-L1400

That breaks the test suite, but I don't believe it breaks at runtime.

And it's actually done in various places.
